### ISSUE TITLE
Shave some more bytes

### ISSUE THREAD

**Issue by RonnyO** [alfg/ping.js#2]
ping.js is already small, and after merging #1 would be smaller; But I suggest the following:
- Shorter banner for minified version
- No version property - Not sure if this is really useful
- Maybe the type checking for callback can be skipped and `callback && callback(pong)` would be enough? Maybe if there's no callback we can default to `console.log` so it's still useful.

WDYT?

**Comment by alfg** [comment]
I agree. When I first created the project, I just used a common template that I normally use on other JS projects, including the versioning property and banners. I also think the type checking can be removed per your suggestion since when I originally created this I was intending to add in other utilities, but really never got around to it. So the cleanup makes sense. :)

**Comment by RonnyO** [comment]
:+1:

**Comment by alfg** [comment]
https://github.com/alfg/ping.js/commit/440ab5e42bd64a32a30372818a5020c13ce000b0
