### ISSUE TITLE
ping ipaddress

### ISSUE THREAD

**Issue by orichienal** [alfg/ping.js#34]
Hi
ich mag dieses Projekt da ich lokal auf meinem Rechner ohne einen Server etwas pingen kann.
Aber nun möchte ich eine feste ip adresse pingen, leider bekomme ich da einen fehler.
Leider bin ich in JavaScript nicht so erfahen und webprogrammierung.
Könnte mir jemand helfen wie ich eine beliebige ipadresse pingen könnte?!?
ich würde gern nicht nur server im internet damit auf erreichbarkeit prüfen sondern auch gern rechner bzw. geräte die in meinem internen Netz laufen sollten.
559 / 5000
Übersetzungsergebnisse
Hi
I like this project because I can ping something locally on my computer without a server.
But now I want to ping a fixed ip address, unfortunately I get an error.
Unfortunately I am not that experienced in JavaScript and web programming.
Could someone help me how I could ping any ip address?!?
I would like to use it not only to check the accessibility of the internet server, but also to check computers or devices that should run in my internal network.

I hope someone can help me in the short term.
Thank you so much
orichienal

**Comment by alfg** [comment]
Hey @orichienal, 

Since JavaScript (and therefore ping.js) doesn't have a native way to send a ping, it simulates it by attempting to load an image from the web server and checks the response time. So the host and/or port must have a webserver to respond. It's a hacky way of "ping", so it has it's faults. You should be able to ping your internal network as long as each host has some type of web server to respond. 

Hope that helps.
